MakeRedisAuthStore Implementation
WhiskeySockets/Baileys pull request #109
Opened 2023-06-06 20:46 UTC by samuelrac

New dependencies:

- cache-manager
- cache-manager-redis-yet
- cache-manager-ioredis-yet

Goal:
Enable Redis to be used natively to save instance keys and credentials.

Way of use:

```
import { redisStore } from 'cache-manager-ioredis-yet'
import { makeRedisAuthState } from '@whiskeysockets/baileys'
```

Start connecting to Redis
```
const redisInstace = await redisStore({
     host: '127.0.0.1',
     port: 6379,
     password: '',
})
```
Instantiate the **makeRedisAuthState** function and inform the Redis connection instance and a key referring to the WPP instance

`const { state, saveCreds, clearState } = await makeRedisAuthState(redisInstance, key)`

2023-06-07 16:28 UTC, edgardmessias commented on package.json
> +    "cache-manager": "^5.2.2",
Add only `cache-manager` as dependency

2023-06-07 16:29 UTC, edgardmessias commented on src/Store/make-in-redis-store.ts
> +import { caching } from 'cache-manager'
```suggestion
import { caching, Store } from 'cache-manager'
```

2023-06-07 16:30 UTC, edgardmessias commented on src/Store/make-in-redis-store.ts
> +const makeRedisAuthState = async(store: IORedisStore | RedisStore, sessionKey: string) => {
```suggestion
const makeCacheManagerAuthState = async(store: Store, sessionKey: string) => {
```

2023-06-07 16:32 UTC, edgardmessias commented on src/Store/make-in-redis-store.ts
> +	const writeData = async(file: string, data: object) => await databaseConn.set(defaultKey(file), JSON.stringify(data, BufferJSON.replacer))
You need to set a default TTL to avoid expiration

2023-06-07 16:33 UTC, edgardmessias commented on src/Store/make-in-redis-store.ts
> +                                await readData(`${type}-${id}`)
```suggestion
							await readData(`${type}-${id}`)
```

2023-06-07 20:01 UTC, ripreal commented
Little remark here. Redis is not good option for heavy whatsapp accounts. Especially for a lot accounts on a single redis node. It is verified on my personal experience.

2023-06-07 22:22 UTC, samuelrac commented
> 
What do you suggest in place of Redis? I have 700 instances connected and I never had a problem, but I would like to know what you suggest that could be better than Redis for me to study in case of any problems?

2023-06-07 22:22 UTC, samuelrac commented
> Little remark here. Redis is not good option for heavy whatsapp accounts. Especially for a lot accounts on a single redis node. It is verified on my personal experience.

What do you suggest in place of Redis? I have 700 instances connected and I never had a problem, but I would like to know what you suggest that could be better than Redis for me to study in case of any problems?

2023-06-09 16:46 UTC, w3nder commented
> > > Little remark here. Redis is not good option for heavy whatsapp accounts. Especially for a lot accounts on a single redis node. It is verified on my personal experience.
> > 
> > 
> > What do you suggest in place of Redis? I have 700 instances connected and I never had a problem, but I would like to know what you suggest that could be better than Redis for me to study in case of any problems?
> 
> I'd recommend move to mongodb

If you save and maintain all the keys in Redis, it won't be optimal because Redis will take longer to perform queries. Samuel's approach is to set a 24-hour expiration time for keys other than "creds", thus avoiding having multiple keys in Redis.

```
let ttl: number | undefined = 86400 // 24 hours
if(file === 'creds') {
	ttl = undefined
}
```

This way, keys other than "creds" will have a 24-hour expiration time, while the "creds" key will have no defined expiration time.

2023-06-09 22:21 UTC, Fonnte commented
Be careful, deleting the keys have it's own down side. I have ever did what you suggest to just because i don't like to save few GB of keys data. But it got me hard. Incoming message will need more time to be decrypted first every the period (in the suggeston, every 24 hours). Some incoming messages would be failed/unable to decrypted due to invalid something or no session (sorry forgot the exact reason) especially from IOS and sending message could take longer to failed. Sometime even return the id when sending mesage but not got delivered in the recipient's phone. I personally wouldn't mess again with the keys. 

All keys should be stored in the database so it could be loaded only when needed. Only after doing that, clearing the data periodically from redis should be okay as it will be loaded again from database when needed.

2023-06-09 22:49 UTC, samuelrac commented
> Be careful, deleting the keys have it's own down side. I have ever did what you suggest to just because i don't like to save few GB of keys data. But it got me hard. Incoming message will need more time to be decrypted first every the period (in the suggeston, every 24 hours). Some incoming messages would be failed/unable to decrypted due to invalid something or no session (sorry forgot the exact reason) especially from IOS and sending message could take longer to failed. Sometime even return the id when sending mesage but not got delivered in the recipient's phone. I personally wouldn't mess again with the keys.

All keys should be stored in the database so it could be loaded only when needed. Only after doing that, clearing the data periodically from redis should be okay as it will be loaded again from database when needed.

Thanks for the suggestion, I'm going to create a parameter that lets the user define how long he'd like to keep the keys and default to 24 hours.  if the user does not set the key expiration time, the default will be 24 hours.

2023-06-12 12:22 UTC, edgardmessias requested changes
For me, I will merge after ttl change.

2023-06-12 12:22 UTC, edgardmessias commented on src/Store/make-cache-manager-store.ts
> +			ttl = undefined
I think we can use `undefined` by default, because the cache-manager instance we can set the default TTL, but for `creds`, we can set some value like 2 years, because some implementations don't allow zero or undefined for unlimited

2023-06-12 14:48 UTC, merged