Dependency Inversion for Logger
WhiskeySockets/Baileys pull request #1153
Opened 2024-12-03 20:36 UTC by MateusFrFreitas

It is very useful to be able to implement your own log library. With this in mind I decided to implement this feature.

The only problem I found was if someone have already used a custom pino instance, it may break their code.

2024-12-06 18:01 UTC, devlikepro commented
IMO, if you need to have custom logger - just pretend to be `pino.Logger`.

In most cases (I believe like 99%) people will just use regular `pino`. why complicate the code with only 1% in mind?

I mean, we probably could define an Interface that maps the features we're using in **pino** (so you have a real base for implementing only necessary feature in custom logger) instead of using adapter for all 99%.
```
export interface ILogger
```
this is fine if it'll follow the pin logger interface 1-1 without `PinoLoggerAdapter` (too complex, imo)

2024-12-09 18:13 UTC, MateusFrFreitas commented
> IMO, if you need to have custom logger - just pretend to be `pino.Logger`.
> 
> In most cases (I believe like 99%) people will just use regular `pino`. why complicate the code with only 1% in mind?
> 
> I mean, we probably could define an Interface that maps the features we're using in **pino** (so you have a real base for implementing only necessary feature in custom logger) instead of using adapter for all 99%.
> ```
> export interface ILogger
> ```
> this is fine if it'll follow the pin logger interface 1-1 without `PinoLoggerAdapter` (too complex, imo)
>    
> 

Thank you for your reply. I'll try to keep the interface and remove the adapter.

2024-12-23 19:33 UTC, purpshell requested changes
I share @devlikepro's sentiment in this case.

2025-01-02 11:41 UTC, MateusFrFreitas commented
Hello, I updated this branch on your advice.

2025-01-10 09:49 UTC, devlikepro approved these changes
And fixed the current debug message - amazing! :+1:

2025-01-12 23:44 UTC, purpshell commented
fix linting

2025-01-13 12:22 UTC, MateusFrFreitas commented
Fixed

2025-01-13 14:36 UTC, purpshell approved these changes

2025-03-01 16:30 UTC, merged