[feat]: add/edit/remove contacts
WhiskeySockets/Baileys pull request #1172
Opened 2024-12-23 14:35 UTC by vinikjkkj

2024-12-23 19:26 UTC, purpshell reviewed
Will test then approve/reject!

2024-12-24 03:13 UTC, azudindaem approved these changes
Tested

```js
const contactAction = {
        "fistName": "first name",
        "fullName": "full name",
        "saveOnPrimaryAddressbook": true
    };
await sock.addOrEditContact(jid, contactAction);
```

2024-12-29 04:35 UTC, rlzyy commented
not working bro

2025-01-01 08:21 UTC, AstroX11 approved these changes

2025-01-30 18:10 UTC, Riders004 commented
> Tested
> 
> ```js
> const contactAction = {
>         "fistName": "first name",
>         "fullName": "full name",
>         "saveOnPrimaryAddressbook": true
>     };
> await sock.addOrEditContact(jid, contactAction);
> ```

What is jid ?

2025-03-01 07:04 UTC, purpshell reviewed
do these things throw out contact update events?

2025-03-01 17:16 UTC, AstroX11 commented
> Tested
> 
> ```js
> const contactAction = {
>         "fistName": "first name",
>         "fullName": "full name",
>         "saveOnPrimaryAddressbook": true
>     };
> await sock.addOrEditContact(jid, contactAction);
> ```

looks incorrect, the functionality was under chatModify function

2025-03-04 11:30 UTC, AstroX11 commented
There's no need having a dedicated function for this in my own point of view everything should be in the Chat modify function

2025-03-11 06:23 UTC, AstroX11 commented
Tested this doesn't work

2025-04-09 16:45 UTC, vinikjkkj commented
apparently whatsapp removed this function, i tested with two numbers, in whatsapp web it not appears anymore.

2025-06-21 03:09 UTC, barkerpedro commented
> apparently whatsapp removed this function, i tested with two numbers, in whatsapp web it not appears anymore.

I tested it recently and it's working perfectly. It added the contact and it appeared on Mobile and Web.

Change the "fistName" to "firstName" and also add the "lidJid" field.

```ts
export type ContactAction = {
    firstName: string
    fullName: string
    lidJid: string | undefined
    saveOnPrimaryAddressbook: boolean
}
```

2025-06-21 04:14 UTC, vinikjkkj commented
reopened, i will work on this again

2025-07-04 10:05 UTC, purpshell requested changes
Lint, resolve merge conflicts, we'll merge.

2025-07-07 19:59 UTC, Santosl2 commented
@vinikjkkj

2025-07-09 04:01 UTC, vinikjkkj commented
updated, tested and working

2025-07-09 19:01 UTC, purpshell approved these changes

2025-07-09 19:01 UTC, merged

2025-07-11 04:08 UTC, mission-sun commented
> Thanks for your contribution.
> 
> The next step is to wait for review and approval to merge it to main repository
> 
> The community can help reacting with a thumb up (:thumbsup:) for approval and rocket (:rocket:) for who has tested it.
> 
> To test this PR you can run the following command below:
> 
> ```
> # NPM
> npm install @whiskeysockets/baileys@vinikjkkj/Baileys-Public#crud-contacts
> # YARN v2
> yarn add @whiskeysockets/baileys@vinikjkkj/Baileys-Public#crud-contacts
> # PNPM
> pnpm add @whiskeysockets/baileys@vinikjkkj/Baileys-Public#crud-contacts
> ```


After downloading, there will be many type errors. How should I use this branch? Please guide me.