feat: memberAddMode and joinApprovalMode in groups.update
WhiskeySockets/Baileys pull request #532
Opened 2023-12-06 05:17 UTC by bobslavtriev

2023-12-07 21:03 UTC, DiegoCarver approved these changes

2023-12-31 23:10 UTC, PurpShell approved these changes
looks good

2024-01-02 02:02 UTC, PurpShell approved these changes
new change is also good.

2024-01-02 02:03 UTC, PurpShell requested changes
fix linting

2024-01-04 19:48 UTC, PurpShell approved these changes
looks good

2024-01-19 15:59 UTC, merged