fix(missing messages): revert to normal
WhiskeySockets/Baileys pull request #732
Opened 2024-04-16 02:38 UTC by PurpShell

Return missing messages logic back to normal so that we get the "Message absent from Node" message. This is because the ack-method only works 90% of the time and we'd like to have direct access for later acknowledgement. 

If in case the ack did not work (10% chance), as it requires the phone of the one who contacted you to be online, simply send another ack:
I've included the raw node so that you don't have to pain yourself in re-constructing a BinaryNode. Just turn it back from JSON to a proper BinaryNode and it should be OK.
```js
sendMessageAck(JSON.parse(msg.messageStubParameters, BufferJSON.reviver))
```

2024-04-16 03:40 UTC, azudindaem requested changes

2024-04-16 03:40 UTC, azudindaem commented on src/Utils/decode-wa-message.ts
```ts
import { unpadRandomMax16, BufferJSON } from './generics'
```

2024-04-16 04:31 UTC, azudindaem commented
I can say that this latest fix successfully addresses the issue of missing messages 100%

```js
if (msg.messageStubParameters && msg.messageStubParameters[0] === "Message absent from node") {
    sock.sendMessageAck(JSON.parse(msg.messageStubParameters[1], BufferJSON.reviver));
}
```

Well done @PurpShell

2024-04-16 14:47 UTC, PurpShell commented on src/Utils/decode-wa-message.ts
> +import { unpadRandomMax16, BufferJSON } from './generics'
```suggestion
import { BufferJSON, unpadRandomMax16 } from './generics'
```

2024-04-17 00:59 UTC, Ludwigyelstein approved these changes

2024-04-17 21:15 UTC, ainitech commented
287 missing messages - 100% recovered using this PR

2024-04-24 16:07 UTC, alejandrB000 commented
> Have received few leads from fb ads, captured appropriately missing messages and sendMessageAck at an interval of ~30 seconds but no message arrived after countless reack. Anyone have similar issue?
> 
> My implementations (more or less)
> 
> ```
> // in message handler
> const missingMessages = {};
> if (msg.messageStubParameters[0] === "Message absent from node") {
>    missingMessages.push({ key: item.key.id, chat_id: item.key.remoteJid, stanza: msg.messageStubParameters[1] });
> }
> 
> // in message recovery handler at interval
> let missingMessage = Messages.getLastMissingMessage(); // get message that has passed 30 seconds span and update interval
> if (missingMessage !== false) {
>    socket.sendMessageAck(JSON.parse(missingMessage.stanza, BufferJSON.reviver));
> }
> 
> // messages.upsert . remove successfully recovery missing message if any
> for (let i = 0; i < missingMessages.length; i++) {
>       let item = missingMessages[i];
>       if (item.key === key && item.chat_id === chat_id) {
>           console.log("successfully recovered message", key, chat_id);
>           missingMessages.splice(i, 1);
>           break;
>       }
>   }
> ```
> 
> If a message is received, it should triggers a reply ![image](https://private-user-images.githubusercontent.com/19306505/325168546-5f1f2683-6647-4aac-b1bb-e7b1f38456d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzQ5MjUsIm5iZiI6MTcxMzk3NDYyNSwicGF0aCI6Ii8xOTMwNjUwNS8zMjUxNjg1NDYtNWYxZjI2ODMtNjY0Ny00YWFjLWIxYmItZTdiMWYzODQ1NmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE2MDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTc3ZTM4NjhmM2U3YTljODg1MDg4YzRiOWRmMjI1YzMyYjc5YTZmMWMwNWVhNDVlZWE1ODZmODFmMWY4NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g-PRLnfsTayPBwVPnxbTtjRm8jaxHUIlJYUuXK3uNAA)

Same thing for me, I am waiting 45 seconds and so far none of the messages have been recovered after sendMessageAck

2024-04-25 19:12 UTC, alejandrB000 commented
> Successfully tested 240 out of 240 messages on FBAds today. 15 were absent, but they've all been recovered using this PR

@azudindaem how long are you waiting before sending the ack? Did it work after the first ack?

2024-04-25 22:07 UTC, azudindaem commented
> > Successfully tested 240 out of 240 messages on FBAds today. 15 were absent, but they've all been recovered using this PR
> 
> @azudindaem how long are you waiting before sending the ack? Did it work after the first ack?

2 method;

1. right after.. utilizing the retry method, we need to verify whether we have received the complete message before stop the process.
2. send an acknowledgment manually using livechat/API.

depending on your implementation, cronjob could also serve our purpose.

2024-04-25 22:36 UTC, canove commented
For those (like me) that keep loosing messages, maybe the mobile phone need to be turned on and WhatsApp open fue yo retry work.

2024-04-26 07:21 UTC, azudindaem commented
> For those (like me) that keep loosing messages, maybe the mobile phone need to be turned on and WhatsApp open fue yo retry work.

exactly

2024-04-26 08:00 UTC, kyraex commented
> For those (like me) that keep loosing messages, maybe the mobile phone need to be turned on and WhatsApp open fue yo retry work.

The mobile phone in question means both of the end users or just the connected device?

2024-04-26 13:49 UTC, alejandrB000 commented
> For those (like me) that keep loosing messages, maybe the mobile phone need to be turned on and WhatsApp open due to retry work.

I've tested it and it does not seems to make any difference

2024-04-27 15:12 UTC, PurpShell commented
@azudindaem actually what @canove mentions here is the target device. So the person you are talking to

2024-04-28 01:23 UTC, Salientekill commented
BufferJSON is not defined.... Do I have to define it?

2024-04-28 01:41 UTC, Salientekill commented
> Have received few leads from fb ads, captured appropriately missing messages and sendMessageAck at an interval of ~30 seconds but no message arrived after countless reack. Anyone have similar issue?
> 
> My implementations (more or less)
> 
> ```
> // in message handler
> const missingMessages = [];
> if (msg.messageStubParameters[0] === "Message absent from node") {
>    missingMessages.push({ key: item.key.id, chat_id: item.key.remoteJid, stanza: msg.messageStubParameters[1] });
> }
> 
> // in message recovery handler at interval
> let missingMessage = Messages.getLastMissingMessage(); // get message that has passed 30 seconds span and update interval
> if (missingMessage !== false) {
>    socket.sendMessageAck(JSON.parse(missingMessage.stanza, BufferJSON.reviver));
> }
> 
> // messages.upsert . remove successfully recovery missing message if any
> for (let i = 0; i < missingMessages.length; i++) {
>       let item = missingMessages[i];
>       if (item.key === key && item.chat_id === chat_id) {
>           console.log("successfully recovered message", key, chat_id);
>           missingMessages.splice(i, 1);
>           break;
>       }
>   }
> ```
> 
> If a message is received, it should triggers a reply ![image](https://private-user-images.githubusercontent.com/19306505/325168546-5f1f2683-6647-4aac-b1bb-e7b1f38456d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjgwODIsIm5iZiI6MTcxNDI2Nzc4MiwicGF0aCI6Ii8xOTMwNjUwNS8zMjUxNjg1NDYtNWYxZjI2ODMtNjY0Ny00YWFjLWIxYmItZTdiMWYzODQ1NmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxMjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZjRkNjIxNDUyMjU1NjgzYzA0NDdmYzVjNDc3MjQxMmM0M2RhMTE2ZDVmZGY1YjljYzYxZTlkOWQzZmUxNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qnBmFLE993IX3TX1wqND2QyRE9nWGO8fmolzjvwZ5pI)

ReferenceError: Messages is not defined

2024-04-28 05:34 UTC, kyraex commented
> > Have received few leads from fb ads, captured appropriately missing messages and sendMessageAck at an interval of ~30 seconds but no message arrived after countless reack. Anyone have similar issue?
> > My implementations (more or less)
> > ```
> > // in message handler
> > const missingMessages = [];
> > if (msg.messageStubParameters[0] === "Message absent from node") {
> >    missingMessages.push({ key: item.key.id, chat_id: item.key.remoteJid, stanza: msg.messageStubParameters[1] });
> > }
> > 
> > // in message recovery handler at interval
> > let missingMessage = Messages.getLastMissingMessage(); // get message that has passed 30 seconds span and update interval
> > if (missingMessage !== false) {
> >    socket.sendMessageAck(JSON.parse(missingMessage.stanza, BufferJSON.reviver));
> > }
> > 
> > // messages.upsert . remove successfully recovery missing message if any
> > for (let i = 0; i < missingMessages.length; i++) {
> >       let item = missingMessages[i];
> >       if (item.key === key && item.chat_id === chat_id) {
> >           console.log("successfully recovered message", key, chat_id);
> >           missingMessages.splice(i, 1);
> >           break;
> >       }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If a message is received, it should triggers a reply ![image](https://private-user-images.githubusercontent.com/19306505/325168546-5f1f2683-6647-4aac-b1bb-e7b1f38456d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjgwODIsIm5iZiI6MTcxNDI2Nzc4MiwicGF0aCI6Ii8xOTMwNjUwNS8zMjUxNjg1NDYtNWYxZjI2ODMtNjY0Ny00YWFjLWIxYmItZTdiMWYzODQ1NmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxMjk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZjRkNjIxNDUyMjU1NjgzYzA0NDdmYzVjNDc3MjQxMmM0M2RhMTE2ZDVmZGY1YjljYzYxZTlkOWQzZmUxNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qnBmFLE993IX3TX1wqND2QyRE9nWGO8fmolzjvwZ5pI)
> 
> ReferenceError: Messages is not defined

This is only an example of how i implement it. Not the actual source . You can take this as an example

2024-04-28 10:39 UTC, merged

2024-07-22 05:57 UTC, Skidy89 commented
yeah but in ts has a undefined error so idk

if u have the same error
if (msg.messageStubParameters[0] != undefined && msg.messageStubParameters[0] === "Message absent from node") {
        await sock sendMessageAck(JSON.parse(msg.messageStubParameters[1], BufferJSON.reviver));
}

pd: 100% works

2025-05-01 10:34 UTC, AstroX11 commented
Works fine and great

2025-09-09 01:41 UTC, rafaelfix commented
> Works fine and great

How did you solve this?
For me, there is no second element in this array:
```[ 'Message absent from node' ]```