Update make-in-memory-store.ts
WhiskeySockets/Baileys pull request #755
Opened 2024-04-30 11:23 UTC by PurpShell

2024-04-30 22:35 UTC, andresayac approved these changes

2024-05-01 13:11 UTC, souravkl11 approved these changes

2024-05-01 13:32 UTC, souravkl11 requested changes
contact = contacts[contactHashes.find(([, b]) => b === update.id)[0] || '']; // find contact by attrs.hash
                                                                                     ^
TypeError: Cannot read properties of undefined (reading '0')

2024-05-03 17:50 UTC, CSFelix commented
I've just tested with this PR and got the following error:

```
backend\node_modules\@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:143
ttrs.hash
                                                                                  
TypeError: Cannot read properties of undefined (reading '0')
at EventEmitter.<anonymous> (\backend\node_modules\@whiskeysockets\baileys\lib\Store\make-in-memory-store.js:143:86)
```

2024-05-03 18:45 UTC, ubarrawandrey15 commented
I have a similar error

```
/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:157
                Object.assign(contacts[update.id], contact);
                       ^

TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at EventEmitter.<anonymous> (/home/ubuntu/buck-bot-on/node_modules/@adiwajshing/baileys/lib/Store/make-in-memory-store.js:157:24)

```

2024-05-06 14:41 UTC, merged