Process newsletter msgs
WhiskeySockets/Baileys pull request #819
Opened 2024-05-24 20:39 UTC by oscarguindzberg

Fixes https://github.com/WhiskeySockets/Baileys/issues/628

2024-05-24 22:31 UTC, azudindaem requested changes

2024-05-24 22:31 UTC, azudindaem commented on src/Utils/decode-wa-message.ts
> +		author = ''
author = from

2024-05-26 00:35 UTC, oscarguindzberg commented on src/Utils/decode-wa-message.ts
> +		author = ''
done

2024-05-26 01:59 UTC, ainitech approved these changes
Ok from here! Tested!

2024-06-04 19:02 UTC, CSFelix commented
The PR worked for me!!

2024-06-04 19:02 UTC, CSFelix approved these changes
LGTM!!

2024-07-27 14:57 UTC, PurpShell commented
#919

2024-07-27 14:57 UTC, closed without merging