Fix: getUSyncDevices
WhiskeySockets/Baileys pull request #862
Opened 2024-06-12 03:53 UTC by bobslavtriev

If there are no users to search for, the query is executed anyway, leaving it 100ms ~ 500ms slower, decreasing performance and consuming unnecessary resources

2024-06-12 05:13 UTC, erickythierry commented
This fix significantly reduces the delay in sending messages.

2024-06-12 05:16 UTC, erickythierry approved these changes
Great fix.

2024-06-12 12:14 UTC, PurpShell requested changes
change code structure

2024-06-14 00:47 UTC, vermaysha commented
look good to me

2024-06-28 23:01 UTC, PurpShell approved these changes

2024-07-25 23:06 UTC, acoBOYZ commented
nice catch!

2024-07-25 23:11 UTC, acoBOYZ approved these changes

2024-07-26 20:21 UTC, T3uZ commented
up

2024-07-27 13:14 UTC, merged