update proto extract method / update protos to 2.300.x (breaking change, ready to merge)
WhiskeySockets/Baileys pull request #894
Opened 2024-06-26 18:58 UTC by vinikjkkj

# Proto 

This update will change access to proto properties, example (`proto.Message` will be `proto.WAE2E.Message`)

# Proto Extract

  

Modified proto-extract from tulir's [whatsmeow](https://github.com/tulir/whatsmeow) method, this version generates protos with extracted javascript modules from whatsapp web, no need to install third-party modules, only `protobufjs-cli`

  

## Usage

1. Download WhatsApp Web javascript modules to `proto.js` file in `proto-extract` folder

2. Install `protobufjs-cli` with yarn or npm

3.  Open terminal shell in proto-extract folder

4. Run `generate.sh` file

5. This script will generate all protos and all statics `.js and .ts`

## TODO

- [x] Fix export protos to use in baileys, in protos that have imports, there is conflicts with imported file. It can be fixed if we put all the protos in a single file, like the old one
- [x] Fix TS files generated from pbts
- [x] Update proto imports in baileys
- [x]  Find some way to import namespaces to proto object

2024-06-30 03:11 UTC, PurpShell commented
will contribute here soon

2024-08-26 13:45 UTC, T3uZ commented
up

2024-10-01 12:08 UTC, qikerrs approved these changes

2024-10-04 16:44 UTC, samuelrac approved these changes

2024-10-04 22:08 UTC, T3uZ commented
up

2024-10-04 22:53 UTC, canove commented
@vinikjkkjV can you resolve the conflits so we can merge this?

2024-10-05 00:16 UTC, vinikjkkj commented
> @vinikjkkjV can you resolve the conflits so we can merge this?

i don't know if purp will merge, apparently it's not how he wants, and he didn't tell me what should be changed, I'm not going to resolve conflicts without being sure it will be merged

2024-10-11 08:42 UTC, qikerrs approved these changes

2024-10-11 08:42 UTC, qikerrs reviewed
Up

2024-10-11 08:42 UTC, qikerrs approved these changes
up

2024-10-11 18:57 UTC, endriodev commented
Up @PurpShell

2024-10-12 18:17 UTC, Lucas-Alves-Silva commented
UP!

2024-10-13 02:24 UTC, HermesMacedo commented
up @PurpShell

2024-10-17 12:20 UTC, samuelrac commented
up @PurpShell

2024-10-22 22:21 UTC, lucaspossam commented
How can I download the protobuff from WhatsApp Web to test this PR? @vinikjkkj

2024-12-13 14:30 UTC, samuelrac commented
UP @purpshell

2024-12-23 19:40 UTC, purpshell requested changes
I don't agree with this course of development. We'll be releasing the WhiskeySocket's ProtoCocktail proprietary protobuf harvesting tool very soon. (this will also be the method determined by whatsmeow and Cobalt as well)

2025-05-21 15:23 UTC, canove commented
closing in favor of https://github.com/WhiskeySockets/Baileys/pull/1457 as it change less code and its just temporary while ProtoCocktail is not ready.

2025-05-21 15:23 UTC, closed without merging